-- 1. CREATE TABLE
CREATE TABLE employee_liquibase_for_prod_testing (
    emp_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR2(50),
    last_name     VARCHAR2(50),
    department    VARCHAR2(50),
    salary        NUMBER(10,2),
    hire_date     DATE DEFAULT SYSDATE
);

-- 2. INSERT (2-3 records)
INSERT INTO employee_liquibase_for_prod_testing (first_name, last_name, department, salary)
VALUES ('John', 'Doe', 'HR', 55000);

INSERT INTO employee_liquibase_for_prod_testing (first_name, last_name, department, salary)
VALUES ('Jane', 'Smith', 'Finance', 72000);

INSERT INTO employee_liquibase_for_prod_testing (first_name, last_name, department, salary)
VALUES ('Robert', 'Brown', 'IT', 68000);

COMMIT;

-- 3. SELECT
SELECT * 
FROM employee_liquibase_for_prod_testing;

SELECT first_name, last_name, department, salary
FROM employee_liquibase_for_prod_testing
WHERE department = 'IT';

-- 4. UPDATE
UPDATE employee_liquibase_for_prod_testing
SET salary = salary + 5000
WHERE department = 'HR';

UPDATE employee_liquibase_for_prod_testing
SET department = 'Operations'
WHERE last_name = 'Smith';

COMMIT;

-- 5. DELETE
DELETE FROM employee_liquibase_for_prod_testing
WHERE last_name = 'Brown';

DELETE FROM employee_liquibase_for_prod_testing
WHERE department = 'HR';

COMMIT;
